[default]
MONGO_URI = "mongodb://localhost:27017/"
# for production inject via DYNACONF_AUTH_SECRET_KEY, to generate: openssl rand -hex 32
AUTH_SECRET_KEY = "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
AUTH_ALGORITHM = "HS256"
AUTH_ACCESS_TOKEN_EXPIRE_MINUTES = 30
API_PORT = 8342
API_HOST = '0.0.0.0'
UVICORN_RELOAD = false

[development]
UVICORN_RELOAD = true
[compose]
MONGO_URI = "mongodb://mongo:27017"
